apiVersion: policy.jspolicy.com/v1beta1
kind: JsPolicy
metadata:
  name: "template.example.com"
spec:
  type: Mutating
  operations: ["CREATE"]
  resources: ["clusters"]
  apiGroups: ["provisioning.cattle.io"]
  objectSelector:               
    matchLabels:
      app: hcloud-cloud-controller-manager
  javascript: |
    const secretName = request.object.spec.cloudCredentialSecretName;
    const secretObject = get("Secret", "v1", secretName.replace(':', '/'));
    const secretValue = atob(Object.values(secretObject.data)[0]);
    const cngValue = request.object.spec.rkeConfig.additionalManifest.replaceAll('REPLACE_TOKEN_TO_CLOUD_CREDENTIAL', secretValue);
    request.object.spec.rkeConfig.additionalManifest = cngValue;
    mutate(request.object);
