apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- patch: |-
    - op: replace
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: MY_ENV
        value: "2"
  target:
    kind: Deployment
    namespace: kube-system
    name: jspolicy